plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs8.github.io # the base hostname & protocol for your site
baseurl: /w19-conrad  # the subpath of your site, e.g. "/blog"


include:
  - _pages
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
  - .bundle

course: "CMPTGCS 20"
qtr: "W20"
qxx: "w20"
instructor: "Conrad"
quarter: "Winter 2020"


name: "CMPTGCS 20, W20, Conrad"
github_url: https://github.com/ucsb-cs8/w20-ccs
baseurl: "/w20-ccs"
url: "https://ucsb-cs8.github.io/w20-ccs"


start_week: 1
start_date: 2020-01-06 
num_weeks: 10
extra_exam_week: true
sections:

cal_dates: >
  [                                                                            
    {"label":"W20 begins", "date":"2020-01-06" },              
    {"label":"Univ Holiday", "date":"2020-01-20" },                            
    {"label":"Univ Holiday", "date":"2020-02-17" },                            
    {"label":"Drop w/o W", "date":"2020-02-03" },                            
    {"label":"DST starts", "date":"2020-03-08" },                            
    {"label":"Classes end", "date":"2020-03-13" },                    
    {"label":"W20 finals start", "date":"2020-03-14" },                        
    {"label":"W20 finals end", "date":"2020-03-20" },                          
    {"label":"W20 qtr ends", "date":"2020-03-20" }                              
  ] 


hwk_drop_lowest: one


kramdown:
   parse_block_html: true

exclude:

timezone: America/Los_Angeles

collections:
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
